name: Debug README Update

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    
    - name: Attempt README Update
      run: |
        current_date=$(date +"%d/%m/%Y")
        last_update=$(date)
        
        # Escape slashes in current_date for use in perl
        escaped_date=$(echo "$current_date" | sed 's/\//\\\//g')
        
        # Use perl to replace text with escaped variables
        perl -pi -e "s/Date de mise à jour : \\d{2}\\/\\d{2}\\/\\d{4}/Date de mise à jour : $escaped_date/" README.md
        perl -pi -e "s/Last update on.*/Last update on $last_update/" README.md
        
        echo "Updated README contents:"
        cat README.md
    
    - name: Commit and Push
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add README.md
        git commit -m "Debug: Update README" || echo "No changes to commit"
        git push
