name: Update README every 30 minutes

on:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README
        run: |
          DATE=$(date +"%d/%m/%Y")
          echo "Date actuelle: $DATE"
          sed -i "s|## Date de mise à jour : .*|## Date de mise à jour : $DATE|" README.md
          cat README.md # Pour vérifier si la mise à jour a réussi

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Mise à jour automatique de la date" -a || true
          git push
