name: Update README

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight UTC every day
  workflow_dispatch:     # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    
    - name: Update README
      env:
        TZ: 'Europe/Paris'  # Set timezone to ensure correct date
      run: |
        # Set the current date and last update line
        current_date=$(date +"%d/%m/%Y")
        last_update_line="Last update on $(date)"
        
        # Escape slashes in current_date for sed
        escaped_date=$(echo "$current_date" | sed 's/\//\\\//g')
        
        # Use sed to replace text in README.md
        sed -i "s/Date de mise à jour : [0-9]\{2\}\/[0-9]\{2\}\/[0-9]\{4\}/Date de mise à jour : $escaped_date/" README.md
        sed -i "s/Last update on.*/$last_update_line/" README.md
    
    - name: Commit changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "github-actions@github.com"
        git add README.md
        
        # Check if there are changes to commit
        if ! git diff --quiet; then
          git commit -m "Update README date"
          git push
        else
          echo "No changes to commit"
        fi
