name: Update README
on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight UTC every day
  workflow_dispatch:     # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Update README
      env:
        TZ: 'Europe/Paris'  # Set timezone to ensure correct date
      run: |
        # Format dates
        current_date=$(date +"%d/%m/%Y")
        last_update=$(date -u "+%a %b %d %H:%M:%S UTC %Y")
        
        # Create a temporary file
        touch temp_readme
        
        # Read the README line by line and make replacements
        while IFS= read -r line; do
          if [[ $line =~ "## Date de mise à jour :" ]]; then
            echo "## Date de mise à jour : $current_date" >> temp_readme
          elif [[ $line =~ "^[*]Last update on" ]]; then
            echo "*Last update on $last_update*" >> temp_readme
          else
            echo "$line" >> temp_readme
          fi
        done < README.md
        
        # Replace original file with updated content
        mv temp_readme README.md
        
        # Debug output
        echo "Updated content:"
        cat README.md

    - name: Commit changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "github-actions@github.com"
        git add README.md
        git diff --cached --quiet || (git commit -m "Update README date [skip ci]" && git push)
