name: Update README

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight UTC every day
  workflow_dispatch:     # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    
    - name: Update README
      env:
        TZ: 'Europe/Paris'  # Set timezone to ensure correct date
      run: |
        current_date=$(date +"%d/%m/%Y")
        last_update_line="Last update on $(date)"
        
        sed -i "s/Date de mise à jour : [0-9]\{2\}\/[0-9]\{2\}\/[0-9]\{4\}/Date de mise à jour : $current_date/" README.md
        sed -i "s/Last update on.*/$last_update_line/" README.md
    
    - name: Commit changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add README.md
        git diff --quiet && git diff --staged --quiet || git commit -m "Update README date"
        git push
