name: Update README Date

on:
  schedule:
    - cron: "*/30 * * * *" # Ce workflow s'exécute toutes les 30 minutes

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Update README Date
        run: |
          DATE=$(date +"%d/%m/%Y")
          sed -i "s|## Date de mise à jour : .*|## Date de mise à jour : $DATE|" README.md

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Automated README date update" -a || exit 0  # Ne pas échouer si aucun changement
          git push
