name: Update README

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight UTC every day
  workflow_dispatch:     # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    
    - name: Update README
      uses: digitalfortress-tech/update-readme@v1
      with:
        commit_message: Update README date
        update_section: true
        section_pattern: '## Date de mise à jour'
        update_last_update_section: true
